### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement torch==1.0.1.post2

### ISSUE THREAD

**Issue by Amokstakov** [abhyantrika/nanonets_object_tracking#11]
Trying to run the README.md

Used pip install -r requirements.txt and got:

  ERROR: Could not find a version that satisfies the requirement torch==1.0.1.post2 (from -r requirements.txt (line 6)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.0.1.post2 (from -r requirements.txt (line 6))

Any thoughts/solutions?

**Comment by CyberCyclone** [comment]
You'll most likely need to update pip. The version that comes with Ubuntu 18.04 is pip 9, so a later version of pip is needed to load most modules.

**Comment by abhyantrika** [comment]
Sorry. That's a bug introduced by pipreqs package, while creating requirements.txt 
You can remove that line and install pytorch 1.0 from offical website.
