### ISSUE TITLE
How to generate the detections text file?

### ISSUE THREAD

**Issue by anzy0621** [abhyantrika/nanonets_object_tracking#12]
Hi, can anyone suggest how to generate detections text file? I used detectron2 but not sure how to output those detections to a text file. Any help would be appreciated.

**Comment by PradeepSinghMakwana** [comment]
There is a comment and solution available here. 
[previous comment](https://github.com/abhyantrika/nanonets_object_tracking/issues/9#issuecomment-593992092)

I have used detectron2 as well,  I made this [repo](https://github.com/PradeepSinghMakwana/sheep_tracking) that solves the problem. 
You can check out predictor.py file, sheepFinder.py file contains format for printing.
