### ISSUE TITLE
How to evaluate the accuracy of tracking?

### ISSUE THREAD

**Issue by Ujang24** [abhyantrika/nanonets_object_tracking#14]
This below is an example of a detection result which is the input for deep_sort.
Later on, the second digit will be changed into an object ID.

In some cases, the tracker failed (wrongly assigned object ID).
It also often makes new IDs for the reappeared object.
What I need to know is how to evaluate the accuracy of tracking so that we can compare this algorithm with other algorithms?

Any help would be appreciated.
---

1,-1,613.5829,88.5738,10.7212,10.5208,-1,-1,-1
1,-1,159.3612,412.3874,11.2697,9.9765,-1,-1,-1
1,-1,612.6691,227.6705,11.7314,9.7182,-1,-1,-1
1,-1,484.7934,39.8948,12.2918,10.8645,-1,-1,-1
1,-1,268.6557,315.8924,11.2140,10.8330,-1,-1,-1
..
2,-1,568.5021,400.1530,10.8805,10.7782,-1,-1,-1
2,-1,135.4661,29.4275,11.4167,9.2357,-1,-1,-1
2,-1,564.1170,315.1545,13.9052,9.7275,-1,-1,-1
2,-1,503.0762,435.7337,11.3504,9.8643,-1,-1,-1
2,-1,611.6464,111.1447,10.4282,12.9108,-1,-1,-1
..

**Comment by abhyantrika** [comment]
Please refer to this:

https://github.com/shenh10/mot_evaluation 

Its a standard evaluation metric as prescribed by MOT.
