### ISSUE TITLE
How to implement lambda in equation 5?

### ISSUE THREAD

**Issue by bingiflash** [abhyantrika/nanonets_object_tracking#17]
It is mentioned official deepsort repo's issues that the author's implementation doesn't contain any lambda(lambda=0). 
https://github.com/nwojke/deep_sort/issues/112#issuecomment-487884003
I want do some experiments with that equation.

Can anyone help me to include that equation into the code.

**Comment by michael-camilleri** [comment]
I am working on a fix on this in my fork. Will let you know once done

**Comment by abhyantrika** [comment]
It is not required. 
The authors note that lambda=0,ie using only deep features actually provides a good enough representation.
