### ISSUE TITLE
The dets is not match the video

### ISSUE THREAD

**Issue by luoling1993** [abhyantrika/nanonets_object_tracking#2]
1. I use the det_ssd512.txt deections, and download the video from readme
2. I found that video have (211(s)*10(FPS)=2110 frames), but in file, only 1995 frames
3. I write the rectangle with cv2, but it didn't select the cars

**Comment by sangnguyenz** [comment]
Same. The detection files don't match the video. I'm implementing this repo with yolo for detection, but the bounding box after tracking is so large than the objects.

**Comment by abhyantrika** [comment]
Please do note that this is NOT a detection dataset. This is based on the NVIDIA AI city challenge dataset which was meant for tracking only. 
So, the detections might have only specific classes filtered out.
Also, regarding large boxes, that's the effect after using kalman filters and other methods. But that should not matter as we do not care about IOU when the object is being tracked.

**Comment by WilliamJuel** [comment]
I'm sorry, I have just opened the same issue that has been closed here. But I feel you don't answer the actual question (the given detections do NOT match the test video). @abhyantrika so is there a chance that you would look at it again?

Is there another video that matches the given detections?
