### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (540,960,3) (1080,1920,3)

### ISSUE THREAD

**Issue by nischaygowda105** [abhyantrika/nanonets_object_tracking#22]
frame = frame * mask
ValueError: operands could not be broadcast together with shapes (540,960,3) (1080,1920,3)

Im getting the above error after giving a Video as input from MARS dataset, to run test_on_video.py file

**Comment by harrysprogramming** [comment]
I also have this issue, did u find a solution?

**Comment by abhyantrika** [comment]
Your video frame size and the example mask given are of different sizes. 
You can simply remove this line and proceed.
