### ISSUE TITLE
Testing on faster rcnn model

### ISSUE THREAD

**Issue by Passionatecricketer** [abhyantrika/nanonets_object_tracking#23]
I have trained a model on faster rcnn to detect the cycle riders in a frame.
I want to assign an unique id to each rider and track their movement with each frame and increase the count once they cross a assigned finishing line
Can please someone let me know how can I use this repository for my use case

Thanks in advance!

**Comment by abhyantrika** [comment]
Refer this : 
https://blog.nanonets.com/object-tracking-deepsort/
