### ISSUE TITLE
Train on my own vehicles dataset

### ISSUE THREAD

**Issue by sangnguyenz** [abhyantrika/nanonets_object_tracking#3]
Can I change the dataset for training this feature extractor. Because my project includes motorbikes, bus, trucks.
Thank you

**Comment by abhyantrika** [comment]
Yes you can. Just make sure you follow the same format ie, if you have "N" different classes, make sure to create "N" folders with the class examples inside the corresponding folders.

**Comment by IamExperimenting** [comment]
@abhyantrika , hope you are doing great. I have a follow-up question about this. Let's say, I have 3 classes namely car, motorbike, bus. 
I have a doubt about creating the folders here.

```
|__car
|    |__car_image1.jpg
|    |__car_image2.jpg
|    |__car_image3.jpg
|__bus
|    |__bus_image1.jpg
|    |__bus_image2.jpg
|    |__bus_image3.jpg
|__motorbike
|    |__motorbike_image1.jpg
|    |__motorbike_image2.jpg
|    |__motorbike_image3.jpg
```
I have another doubt when I downloaded the example from this repository under the crops folder there are 329 folders and each folder contains samples of the same car images at a different angle. Here my questions raise, do we need to create a folder for each and every car like a separate folder green colour car and place the images of the green colour car inside it. And a separate folder for red colour car and place the images of the red colour car inside it. should it be like the below folder structure?
```
|__car
|    |_green_car
|    |  |__green_car_image1.jpg
|    |  |__green_car_image2.jpg
|    |  |__green_image3.jpg
|    |_red_car
|    |  |__red_car_image1.jpg
|    |  |__red_car_image2.jpg
|    |  |__red_car_image3.jpg

```

3. Last question, what would be the minimum number of images to be considered for each class?
