### ISSUE TITLE
MOT results sucks using siamese network

### ISSUE THREAD

**Issue by zengjie617789** [abhyantrika/nanonets_object_tracking#32]
I test deepsort + siamese network under MOT eval, here is the results below:
![image](https://user-images.githubusercontent.com/25050291/122899080-11a07300-d37e-11eb-961f-08577882cbd9.png)
It hardly show any improvements than official deepsort results, i am confused that whether i use it properly.
I will be much  appreciate if anyone who can help me, thank you in advance.

**Comment by abhyantrika** [comment]
The objective of this repo is to get people started on how to build an object tracking pipeline that incorporates A generic object detector  + deep sort based tracking. 
To obtain competitive results on MOT and other datasets, you might need to significantly tweak the siamese network, maybe even have a different network.
