### ISSUE TITLE
version compatibility issue

### ISSUE THREAD

**Issue by IamExperimenting** [abhyantrika/nanonets_object_tracking#41]
Hi @abhyantrika , I have tried to install the requirements.txt file, but unfortunately i'm unable install the the python packages. get below issue, could you please tell me the exact versions(python and other python modules) which you used?
![image](https://user-images.githubusercontent.com/74839416/142510442-0534bf2e-5aef-495f-a27e-e5c39b54e93c.png)

**Comment by abhyantrika** [comment]
You can download older versions from [Here](https://pytorch.org/get-started/previous-versions/)
