### ISSUE TITLE
Worse result than the original repo

### ISSUE THREAD

**Issue by quocnhat** [abhyantrika/nanonets_object_tracking#7]
hi, I have implemented and compared the result on vehicle tracking & counting and see that the original deep sort performs better. .,i.e,It switches ID in very short occlusions. 
This repo re-trained cnn to extract embedding for vehicles. From this, it must be better performance than the original (cnn for people features).
Should I fine-turn any hyperparameters or somethings? Thank you

**Comment by abhyantrika** [comment]
Yes. 
It is advised to change hyper parameters accordingly. The starter code here is only for reference and understanding.
